### ISSUE TITLE
Close database connection?

### ISSUE THREAD

**Issue by RingWong** [dcrosta/flask-pymongo#106]
When I running the quickstart example, do I need to close database connection? or it will be closed automatically?
```
from flask import Flask
from flask_pymongo import PyMongo

app = Flask(__name__)
mongo = PyMongo(app)

@app.route('/')
def home_page():
    online_users = mongo.db.users.find({'online': True})
    # mongo.db.close()
    return render_template('index.html',
        online_users=online_users)
```

**Comment by dcrosta** [comment]
Hi @RingWong -- you basically shouldn't do this. PyMongo, like most database drivers, maintains a connection pool from your application to the database server in order to ensure that requests are as fast as possible (ie so that each request doesn't have to establish a new connection).

It doesn't sound like it, but I'd be remiss if I didn't ask: do you have some specific needs or use case where closing the connection is desirable?

**Comment by dcrosta** [comment]
Closing this now, but please update if you still have any questions.

**Comment by RingWong** [comment]
Hi @dcrosta 
Thank you for your help. I just curious for  it, which without closing the connection explicitly.

**Comment by BlonDev** [comment]
Hi Dan @dcrosta ,
Can I re-open this issue? Or, at least comment on it?

I am having an issue with far too many connections remaining open to the point that the MongoDB Atlas connections limit becomes maxed out. I can upgrade for more connections, and will do before deploying to production, but I fear upgrading will not actually solve the problem.

This is regarding a flask app served from Google Cloud, GAE Standard Environment, which spins up app instances dynamically.

My first question for you: How many connections should remain open in the connection pool maintained by PyMongo? Is there a standard number?

Looking forward to your response,
Rose
