### ISSUE TITLE
Support PyMongo 3.0+

### ISSUE THREAD

**Issue by xealot** [dcrosta/flask-pymongo#59]
I apologize if this has been covered already but searching through PRs and closed tickets I could not find any reason why PyMongo is limited to pre-3.0 versions nor can I see any public discussion about why Flask-Pymongo wouldn't be trying to update to use 3.0+ driver versions.

**Comment by dcrosta** [comment]
Hi @xealot -- this is something I intend to support as time permits. I cut a new release a few days ago which limited to PyMongo 2.x because there are incompatibilities between 2.x and 3.x, and I haven't had time to sort through it all yet. If you want to put in the legwork, I'll happily accept a pull request, but I haven't had time to think about it myself yet.

**Comment by xealot** [comment]
Alright, I just wanted to make sure there wasn't already some sort of dialog in place on the 3.x driver line. We will take a look at it and see what's involved.

**Comment by tdterry** [comment]
+1 for 3.0 support. I made a very brief attempt to make Flask-PyMongo work with 3.0 and failed miserably. They really did change a lot of internals.

**Comment by TooAngel** [comment]
+1

**Comment by useyourfeelings** [comment]
+1
When using python3, PyMongo2.x will fail due to gevent problems.
But PyMongo-3.0.2 works.

**Comment by markunsworth** [comment]
This is fixed in #63

**Comment by paulocheque** [comment]
+1
