### ISSUE TITLE
MONGO_CONNECT ignored if MONGO_URI used

### ISSUE THREAD

**Issue by dwieeb** [dcrosta/flask-pymongo#73]
This may turn into a general discussion of how options should work in this library.

I'm using `MONGO_URI`, but I want to set `MONGO_CONNECT` to `False`. When I call `init_app`, it sees that I am using `URI` and thus all other options are ignored (https://github.com/dcrosta/flask-pymongo/blob/75d9877037d509e7d8e2a5ea462ebc8e01420da1/flask_pymongo/__init__.py#L128). I have to manually add `?connect=false` into my connection uri. But my connection uri is just an environment variable and I don't want to manipulate it.

I personally think if, when using `MONGO_URI`, a config value is supplied and the corresponding uri option is not, the config value should be set instead of being thrown away.

**Comment by RezaOptic** [comment]
i have this problem too 
my config is 
```
class DevConfig(object):
    DEBUG = True
    MONGO_URI = "mongodb://localhost:27017/test"
    MONGO_CONNECT = False
    MONGO_MAX_POOL_SIZE = 200
```

but when i connect to DB MONGO_CONNECT is True and MONGO_MAX_POOL_SIZE is None

**Comment by dcrosta** [comment]
I can certainly sympathize with the confusion here. Ultimately, though, I don't think that having Flask-PyMongo try to guess how to mix and match is going to be a great move. If anything, I fear it will cause more confusion and mistakes. I'm going to begin work on Flask-PyMongo 2.0 soon which will probably do away with the options altogether, and just accept URIs.

I'm going to close #81 without merging, but I'll leave this open for discussion for a while longer in case you (@hbldh) or anyone else has additional opinions.

**Comment by dwieeb** [comment]
@dcrosta @hbldh Looking back at this I disagree with myself. Keep it simple. `MONGO_URI` nullifies all supplied connection-related config. If you are _given_ a connection string by a host and want to maintain the ease and safety of copy/paste, just use [urllib.parse](https://docs.python.org/3/library/urllib.parse.html).

**Comment by hbldh** [comment]
@dcrosta I agree with you in part: I agree that having two different means of configuring is a undesired. However, I find that using environment flags as configuration overrides keeps my code much more clean and transparent. 

An example: I often deploy my Flask apps on Heroku. It is very simple to provision a MongoDB database there, and when you have done that a `MONGO_URI` environment variable is added to your app. If all options are to be added in the URI, as you suggest, I have two options if I want to keep all my database client configuration in environment variables:
1) Modify the generated `MONGO_URI` environment variable. I am reluctant to do this since it was generated by Heroku and not by me.
2) Add options to uri via `urllib.parse` or similar in Flask config from my own environment flags. This transfers complexity from Flask-PyMongo to my app(s), something I generally dislike as a developer.

I find it very nice to use the provided `MONGO_URI` directly and then set any additional settings via the configuration flags and have it all handled inside the Flask-PyMongo.

If the price to pay for having only one obvious way to configure Flask-PyMongo is that I have to handle options by myself, I can accept that. But know that at least one person thinks that environment flags that take precedence still serves a purpose.

And thank you for giving some time to Flask-PyMongo again, I really appreciate it!

**Comment by dcrosta** [comment]
@hbldh what options do you find you're typically overriding that aren't set in the connection string?

**Comment by markunsworth** [comment]
Rather than trying to decide how to handle all the possible permutations it why not just pass the URI and all specified options directly to PyMongo and just let it handle it in the documented way.  

I'd be quite disappointed to lose the ability to set all options individually as we currently can - just because it would mean changing the way we do stuff now.

**Comment by hbldh** [comment]
@dcrosta I always set the `MONGO_CONNECT` flag (reason stated in #87) to `False`. I have also used `MONGO_READ_PREFERENCE` several times, as well as `MONGO_DOCUMENT_CLASS`, even though not very often.
On one occasion also `MONGO_SERVER_SELECTION_TIMEOUT_MS` to force app to read from localhost only (deployment was not on Heroku)...

As @markunsworth says, it is a shame to lose the fine grained control that is present now.

**Comment by dcrosta** [comment]
Would it suffice to do something like this:

```python
app = Flask(__name__)
mongo = PyMongo(app, connect=False)
```

For at least some options (I haven't tested exhaustively), passing kwargs to `MongoClient` overrides what is in the connection string:

```python
>>> client = pymongo.MongoClient("mongodb://localhost:27017/?maxPoolSize=100", maxPoolSize=20)
>>> client.max_pool_size
20
```

**Comment by hbldh** [comment]
Having a kwargs on `PyMongo` that is passed to the Mongo client object would work ok for me.

I like it less than how it is right now though, because the natural place to parse env vars for the kwargs will now be in __init__.py for the app instead of in my separate config file.

**Comment by dcrosta** [comment]
I think you could keep parsing wherever you have it now, and do something like:

```python
mongo = PyMongo(
    app,
    maxPoolSize=app.config.MONGO_MAX_POOL_SIZE,
)
```

It's a bit more verbose, because Flask-PyMongo isn't doing any magic for you; but I am leaning towards considering that a benefit rather than a drawback for most use cases.

**Comment by markunsworth** [comment]
What about allowing the option of passing a ready configured mongoclient?

**Comment by dcrosta** [comment]
What would be the point of Flask-PyMongo then, just the helpers?

Actually, maybe that's a good question -- what _should_ Flask-PyMongo be and do?

**Comment by hbldh** [comment]
I agree, parsing can still be done in proper place. However, I think the suggestion you gave above is somewhat backwards. Sending in `app` and then specific options that is present in `app` object. I understand what you are trying to get at, but I think handling such options should be done inside the `PyMongo` init. The suggestion is practical but not very pythonic in my opinion.

**Comment by hbldh** [comment]
I was thinking an `init_app` function more on the lines of this:
```python
convs = {
            'URI': ('uri', str),
            'HOST': ('host', str),
            'PORT': ('port', int),
            'MAX_POOL_SIZE': ('maxPoolSize', int),
            'CONNECT': ('connect', bool),
            'REPLICA_SET': ('replicaSet', str),
            'READ_PREFERENCE': ('readPreference', int),
            # TODO: All other possible kwargs
        }

def init_app(self, app, config_prefix='MONGO'):
     """Initialize the `app` for use with this :class:`~PyMongo`. This is
     called automatically if `app` is passed to :meth:`~PyMongo.__init__`.

    The app is configured according to the configuration variables
    ``PREFIX_HOST``, ``PREFIX_PORT``, ``PREFIX_DBNAME``,
    ``PREFIX_AUTO_START_REQUEST``, ``PREFIX_REPLICA_SET``,
    ``PREFIX_READ_PREFERENCE``, ``PREFIX_USERNAME``,
    ``PREFIX_PASSWORD``, ``PREFXI_AUTH_SOURCE``, ``PREFIX_AUTH_MECHANISM``,
    and ``PREFIX_URI`` where "PREFIX" defaults to "MONGO". If ``PREFIX_URL``
    is set, it is assumed to have all appropriate configurations, and the
    other keys are overwritten using their values as present in the URI.

    :param flask.Flask app: the application to configure for use with
       this :class:`~PyMongo`
    :param str config_prefix: determines the set of configuration
       variables used to configure this :class:`~PyMongo`
    """

    if 'pymongo' not in app.extensions:
        app.extensions['pymongo'] = {}

    if config_prefix in app.extensions['pymongo']:
        raise Exception('duplicate config_prefix "%s"' % config_prefix)

    settings = {
        k.lstrip(config_prefix).lstrip('_'): v for k, v in
        app.config.items() if k.startswith(config_prefix)}
    kwargs = dict([(convs.get(k)[0], convs.get(k)[1](v)) for
                       k, v in settings.items() if k in convs])
    dbname = settings.pop('DBNAME', default=app.name)

    if 'uri' in kwargs:
        uri = kwargs.pop('uri')
        cx = MongoClient(uri, **kwargs)
    else:
        cx = MongoClient(**kwargs)
    db = cx[dbname]
   
    # TODO: Auth from settings dict or user, pwd from uri

    app.extensions['pymongo'][config_prefix] = (cx, db)
    app.url_map.converters['ObjectId'] = BSONObjectIdConverter
```
This uses uri if present and overrides with other config values, otherwise uses host, port and other app config items to configure the client.

This is not a complete init, I know, but it is on the lines of what I would want. I think the approach might work, but I haven't tested it more that that it parses values properly in Python 3.
Much less default value handling and such that makes up large part of the init right now however, making it more concise and manageable IMO.

**Comment by dcrosta** [comment]
I'm still a little worried about the possibility for ambiguity and confusion. What if you specify both URI and MONGO_HOST? I guess we can/should raise an exception.

Another idea I've been playing with that might meet your needs is a tool which modifies a URI given extra arguments -- so like:

```python
original_uri = app.config["MONGO_URI"]
final_uri = flask_pymongo.update_uri(
    original_uri,
    read_preference=app.config["MONGO_READ_PREFERENCE"],
    # ...
)
```

This would make it explicit and intentional that you're overriding the URI, or portions of it; and would simplify the "main" interface to just accept a URI, which I think I want to have be true for 2.0.

**Comment by markunsworth** [comment]
Correct me of I'm wrong but Host and URI are the only two things you can't
set both of in pymongo.MongoClient everything else you can set in the URI
and also provide as a kwarg.

In which case why not just have a single option in flask-pymongo config
(MONGO_HOST) which can either be the host server or a full URI and it's
just passed straight through to pymongo.MongoClient as the 1st parameter.
Then let pymongo deal with the ambiguity on other options

**Comment by hbldh** [comment]
The Host/Uri situation is problematic. I prefer using uri:s for configuring my PyMongo client so I like your intention, but I would also like you to expose and preserve as much of the original PyMongo API as possible so that Flask-PyMongo is an as thin wrapper as possible. The PyMongo `uri_parser` could be extended with `update_uri` and/or `build_uri`, but it adds an additional layer of handling.

The host/uri problem is a imposed by PyMongo. I agree with @markunsworth, keeping MONGO_HOST, removing MONGO_URI and letting PyMongo deal with the any ambiguity of the options and throw exceptions if needed.

**Comment by lyb0525** [comment]
hi，  i think : MONGO_URI = 'mongodb://localhost/test?connect=false'
is useful

**Comment by sam-untapt** [comment]
This is a good discussion.

I have a number of services in a Kubernetes cluster. They share the same secrets. For various reasons some of these services should only connect to the secondaries in our mongo replicaset.

My workaround is to have 2 URIs in my config:
`MONGO_URI: mongodb://mongoX,mongoY,mongoZ/mydb?replicaSet=my-mongo-set`
`MONGO_URI_RO: mongodb://mongoX,mongoY,mongoZ/mydb?replicaSet=my-mongo-set&readPreference=secondary`

And then for the apps that should use the secondaries only:

    app.config['MONGO_URI'] = app.config['MONGO_URI_RO']
    mongo_db.init_app(app)


I began looking at modifying the URI, similar to update_uri() above, but it felt wrong which led me here.

If I understand the above correctly, while the MONGO_HOST keeps everything clean, I would still continue with the above approach. i.e. I would not have one MONGO_URI and in the app explicitly state the Read Preference.

**Comment by asahaf** [comment]
URI option overwrites not only MONGO_CONNECT but all other options if they are set as individual settings but not provided in the URI. I've create a pull request #109 to fix this issue. If the setting is not provided in the URI, it should not overwrite the setting with default

**Comment by dcrosta** [comment]
Hi all. First of all, thanks for all the feedback and ideas over the more than 2 years (!) this issue has been open. I've been really negligent with this project, and I apologize for that. I will try to do better.

As mentioned in #110, I've decided (roughly) that the route we're going to take for an upcoming Flask-PyMongo 2.0 is to rely primarily on the URI for configuration, but allow keyword args to be passed to the `PyMongo` object for advanced configuration. This will net us behavior that's much more similar, if not identical, to PyMongo itself.

I'm going to close this issue now, since the original issue won't be fixed in 0.x, and won't exist (I hope!) in 2.x. I welcome feedback and discussion on #110 though -- please head that way!
